keyserver hkps://keys.openpgp.org

# Retrieve
#gpg --auto-key-locate keyserver --locate-keys user@example.net

# Refresh 
#gpg --refresh-keys

# Upload
#gpg --export jeon@ptrtoj.com | curl -T - http://localhost:8080

