#
# personal configuration
#

#export GPG_TTY=$(tty)
#export PATH="$HOME/.local/bin:$PATH"

export VISUAL="nvim"
export EDITOR="nvim"

#alias e="emacs -nw"
alias v="nvim"
alias vi="nvim"
alias vim="nvim"
