# Add below to default '.bashrc'
# cat .basrc >> ~/.bashrc

# If using daemon, "emacsclient -nc"
alias e="emacs"
alias v="nvim"
alias vi="nvim"
alias vim="nvim"

export EDITOR="$VIM"
export VISUAL="$VIM"
export LANG="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"
export PATH="$HOME/.local/bin:$PATH"

shopt -s autocd
shopt -s histverify
shopt -s cdspell
shopt -s dotglob
shopt -s nocaseglob
shopt -s checkwinsize
shopt -s histappend

HISTSIZE=10000
HISTFILESIZE=50000
HISTCONTROL=ignoreboth

# uncomment for a colored prompt, if the terminal has the capability; turned
# off by default to not distract the user: the focus in a terminal window
# should be on the output of commands, not on the prompt
force_color_prompt=yes

if [ -n "$force_color_prompt" ]; then
    if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
	# We have color support; assume it's compliant with Ecma-48
	# (ISO/IEC-6429). (Lack of such support is extremely rare, and such
	# a case would tend to support setf rather than setaf.)
		color_prompt=yes
    else
		color_prompt=
    fi
fi

# uncomment to enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if [ -f /etc/bash_completion ] && ! shopt -oq posix; then
    . /etc/bash_completion
fi

# Custom Prompt: λ
PS1='\[\e[0;91m\]<\[\e[0;91m\]$?\[\e[0;91m\]> \[\e[0m\][\[\e[0m\]\!\[\e[0m\]] \[\e[0m\](\[\e[0m\]\H\[\e[0m\]) \[\e[0m\]\w \[\e[0;93m\]$(git branch 2>/dev/null | grep '"'"'^*'"'"' | colrm 1 2)\n\[\e[0m\]\u \[\e[0;1;92m\]λ \[\e[0m\]'