#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

if polybar -m | cut -d ':' -f 1 | grep -i hdmi; then
    xrandr --output eDP --below HDMI-A-0
    bspc wm -O eDP HDMI-A-0
    bspc monitor eDP -d 1 2 3 4
    bspc monitor HDMI-A-0 -d 5 6 7 8
else
    bspc monitor -d 1 2 3 4 5 6 7 8
fi
xrandr --output eDP

bspc config border_width         2

bspc config active_border_color  "#CC241D"
bspc config focused_border_color "#D79921"
bspc config normal_border_color  "#928374"
bspc config top_padding          3
bspc config window_gap           5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# autostart
xset -dpms s off
xsetroot -cursor_name left_ptr

# urxvt terminal requires '$xrdb -merge', but it's already handled via '.xinitrc'
urxvtd --quiet --opendisplay --fork

picom -b --experimental-backends
~/.fehbg
${HOME}/.config/polybar/launch.sh
sxhkd &
dunst &

# add to '/etc/environment' below,
#GTK_IM_MODULE=ibus
#QT_IM_MODULE=ibus
#XMODIFIERS=@im=ibus
# decided to manually start, if needed.
# cause it brings alot of hiccups :/
#ibus-daemon -drxR
